### PR TITLE
chore: removed minor extra spacing

### PR DESCRIPTION
**Pull request by harshilparmar**
Hello, I made very minor changes to the documentation. I hope you like it. I am trying open source for the first time from your repo and also learning from your code. Thanks!!!

### CODE REVIEW

**Comment by alioguzhan** [comment]
Hey, Thanks for the fixes! This is exactly how I started to contribute to open source projects. Keep going!

**Comment by alioguzhan** [comment]
One thing that I can suggest that make your commit messages in present tense form. Not past tense. See below resources:

- https://chris.beams.io/posts/git-commit
- https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/
- https://www.conventionalcommits.org

**Comment by harshilparmar** [comment]
Thank you so much !!!

**Comment by alioguzhan** [comment]
@all-contributors please add @harshilparmar for docs

**Pull request merged**
