### PR TITLE
Fix Errors types 

### PR DESCRIPTION
**Pull request by wesoft-systems**
ERROR in [at-loader] ./node_modules/react-editext/index.d.ts:34:23 
    TS2370: A rest parameter must be of an array type.

ERROR in [at-loader] ./node_modules/react-editext/index.d.ts:39:29 
    TS2370: A rest parameter must be of an array type.

ERROR in [at-loader] ./node_modules/react-editext/index.d.ts:54:18 
    TS2370: A rest parameter must be of an array type.

### CODE REVIEW

**Comment by wesoft-systems** [comment]
Plis go head ...

**Comment by wesoft-systems** [comment]
@alioguzhan fix this error; is easy to check. can you merge it??. 
greetings from Mexico

**Comment by alioguzhan** [comment]
Hey @wesoft-systems ! Thanks for the PR. I believe we can fix this by converting `...args: string` to `...args: string[]`. Can you try and update your PR. Example:

```ts
validation?: (...args: string[]) => boolean;
```

**Comment by wesoft-systems** [comment]
@alioguzhan thanks for answer me, send a new change; you were right, i can fix with string[]; any is a lazy mode...   hahahaha.

**Comment by alioguzhan** [comment]
Thanks for the fix! Merging it... @wesoft-systems

**Comment by wesoft-systems** [comment]
@alioguzhan thanks... you rock... \m/

**Comment by alioguzhan** [comment]
You're welcome! I also published a new version with this fix to NPM. Please see npm page and CHANGELOG @wesoft-systems

**Comment by alioguzhan** [comment]
@all-contributors let's add @wesoft-systems for code

**Pull request merged**
