### PR TITLE
fix(validation): allow to pass async functions as validator

### PR DESCRIPTION
**Pull request by mumot1999**

### CODE REVIEW

**Comment by alioguzhan** [comment]
This breaks the existing working code. Because now the `validation` prop required to be an async function. Which is something we do not want to be implemented. We need to handle both situations. Let me think about that

**Comment by mumot1999** [comment]
@alioguzhan sync validation works too

**Comment by alioguzhan** [comment]
Yes, but it defers the execution of the validate function, **even if it is not an async function**.  See below response, please:

https://stackoverflow.com/a/53113299/1510671

That and tests are also failing with this update. I need to figure out what is happening on the jest side.

**Comment by alioguzhan** [comment]
I will re-write this component from scratch with Typescript and hooks, soon. But I don't have enough time these days. 

If you can make all tests in this PR, it is also fine. Or,

What about you use the `onSave` callback and implement your own custom validation on the parent component? Does that work for you?

**Comment by harshilparmar** [comment]
> I will re-write this component from scratch with Typescript and hooks, soon. But I don't have enough time these days.

I would love to help for migration and learn from you 🙇

**Comment by alioguzhan** [comment]
> > I will re-write this component from scratch with Typescript and hooks, soon. But I don't have enough time these days.
> 
> I would love to help for migration and learn from you 🙇

Sure! I will add you to the PR once I start the migration. Another second pair of eyes for review would be great for me. I will ping you. Thanks! @harshilparmar

**Pull request closed without merging**
